# Generated by Django 5.1.3 on 2024-12-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecomendacionMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.IntegerField()),
                ('recomendaciones', models.TextField()),
                ('images', models.TextField()),
                ('description', models.TextField()),
                ('lat', models.TextField()),
                ('lng', models.TextField()),
            ],
        ),
    ]
